import { execFile } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, extname, relative, resolve, sep } from "node:path";
import { promisify } from "node:util";
import { fileURLToPath } from "node:url";

const VERSION_MARKER = `?${"v="}`;
const repositoryRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const reportPath = resolve(repositoryRoot, "docs", "migration_cost.md");
const scannedExtensions = new Set([".css", ".html", ".js", ".json", ".md", ".mjs", ".ps1", ".yaml", ".yml"]);
const execFileAsync = promisify(execFile);

function toRepositoryPath(filePath) {
  return relative(repositoryRoot, filePath).split(sep).join("/");
}

async function discoverTextFiles() {
  const { stdout } = await execFileAsync("git", ["ls-files", "-z"], {
    cwd: repositoryRoot,
    encoding: "utf8",
    maxBuffer: 10 * 1024 * 1024,
  });

  return stdout
    .split("\0")
    .filter(Boolean)
    .filter((filePath) => scannedExtensions.has(extname(filePath).toLowerCase()))
    .map((filePath) => resolve(repositoryRoot, filePath))
    .filter((filePath) => filePath !== reportPath);
}

function findVersionTokens(source, filePath) {
  const occurrences = [];
  const lines = String(source).split(/\r?\n/);

  lines.forEach((line, lineIndex) => {
    let searchFrom = 0;
    while (searchFrom < line.length) {
      const markerIndex = line.indexOf(VERSION_MARKER, searchFrom);
      if (markerIndex === -1) {
        break;
      }

      const valueStart = markerIndex + VERSION_MARKER.length;
      let valueEnd = valueStart;
      while (valueEnd < line.length && /[A-Za-z0-9._-]/.test(line[valueEnd])) {
        valueEnd += 1;
      }

      occurrences.push({
        filePath,
        line: lineIndex + 1,
        column: markerIndex + 1,
        token: line.slice(markerIndex, valueEnd),
        value: line.slice(valueStart, valueEnd),
      });
      searchFrom = Math.max(valueEnd, valueStart);
    }
  });

  return occurrences;
}

async function collectVersionTokens() {
  const occurrences = [];
  for (const absolutePath of await discoverTextFiles()) {
    const filePath = toRepositoryPath(absolutePath);
    const source = await readFile(absolutePath, "utf8");
    occurrences.push(...findVersionTokens(source, filePath));
  }
  return occurrences.sort((left, right) => (
    left.filePath.localeCompare(right.filePath)
    || left.line - right.line
    || left.column - right.column
  ));
}

function escapeTableCell(value) {
  return String(value).replaceAll("|", "\\|");
}

function locationLink(occurrence) {
  const target = `../${occurrence.filePath.replaceAll(" ", "%20")}#L${occurrence.line}`;
  return `[${occurrence.filePath}:${occurrence.line}:${occurrence.column}](${target})`;
}

function renderMigrationCostReport(occurrences) {
  const fileCount = new Set(occurrences.map((occurrence) => occurrence.filePath)).size;
  const uniqueTokens = [...new Set(occurrences.map((occurrence) => occurrence.token))].sort();
  const lines = [
    "# Mapbox v3 Migration Cost",
    "",
    "Generated by `node eng/estimate_migration_cost.mjs`.",
    "",
    "## Summary",
    "",
    `- Query-version occurrences: ${occurrences.length}`,
    `- Files containing query-version tokens: ${fileCount}`,
    `- Unique query-version tokens: ${uniqueTokens.length}`,
    "- Scope: Git-tracked CSS, HTML, JavaScript, JSON, Markdown, PowerShell, and YAML text files.",
    "- Exclusion: this generated report, to prevent recursive self-inventory.",
    "",
    "Each occurrence is a browser cache-busting dependency edge to review during a Mapbox v3 rollout. The count is an inventory, not an engineering-time estimate.",
    "",
    "## Inventory",
    "",
    "| Token | Location |",
    "| --- | --- |",
  ];

  for (const occurrence of occurrences) {
    lines.push(`| \`${escapeTableCell(occurrence.token)}\` | ${locationLink(occurrence)} |`);
  }

  lines.push("", "## Unique Tokens", "");
  for (const token of uniqueTokens) {
    lines.push(`- \`${token}\``);
  }
  lines.push("");
  return lines.join("\n");
}

async function writeMigrationCostReport() {
  const occurrences = await collectVersionTokens();
  await writeFile(reportPath, renderMigrationCostReport(occurrences), "utf8");
  return occurrences;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const occurrences = await writeMigrationCostReport();
  const fileCount = new Set(occurrences.map((occurrence) => occurrence.filePath)).size;
  console.log(`Wrote docs/migration_cost.md with ${occurrences.length} occurrences across ${fileCount} files.`);
}

export {
  VERSION_MARKER,
  collectVersionTokens,
  findVersionTokens,
  renderMigrationCostReport,
  writeMigrationCostReport,
};
